services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    networks:
      - bcci-app

  db:
    image: mysql:8.0.34
    ports:
      - 3306:3306
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-password}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE:-bcci_db}"
      MYSQL_USER: "${DB_USERNAME:-dbuser}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - bcci_mysql_db:/var/lib/mysql
    networks:
      - bcci-app

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8001:80
    depends_on:
      - db
    command: "php artisan schedule:work"
    networks:
      - bcci-app

networks:
  bcci-app:
    driver: bridge

volumes:
  bcci_mysql_db:
